Currency_select_populator = [
    {"currency" => "EUR - Euro", "initialism" => "EUR"},
    {"currency" => "USD - US Dollar", "initialism" => "USD"},
    {"currency" => "JPY - Japanese Yen", "initialism" => "JPY"},
    {"currency" => "BGN - Bulgarian Lev", "initialism" => "BGN"},
    {"currency" => "CZK - Czech Koruna", "initialism" => "CZK"},
    {"currency" => "DKK - Danish Krone", "initialism" => "DKK"},
    {"currency" => "GBP - Pound Sterling", "initialism" => "GBP"},
    {"currency" => "HUF - Hungarian Forint", "initialism" => "HUF"},
    {"currency" => "PLN - Polish Zloty", "initialism" => "PLN"},
    {"currency" => "RON - Romanian Leu", "initialism" => "RON"},
    {"currency" => "SEK - Swedish Krona", "initialism" => "SEK"},
    {"currency" => "CHF - Swiss Franc", "initialism" => "CHF"},
    {"currency" => "NOK - Norwegian Krone", "initialism" => "NOK"},
    {"currency" => "HRK - Croatian Kuna", "initialism" => "HRK"},
    {"currency" => "RUB - Russian Rouble", "initialism" => "RUB"},
    {"currency" => "TRY - Turkish Lira", "initialism" => "TRY"},
    {"currency" => "AUD - Australian Dollar", "initialism" => "AUD"},
    {"currency" => "BRL - Brazilian Real", "initialism" => "BRL"},
    {"currency" => "CAD - Canadian Dollar", "initialism" => "CAD"},
    {"currency" => "CNY - Chinese Yuan Renminbi", "initialism" => "CNY"},
    {"currency" => "HKD - Hong Kong Dollar", "initialism" => "HKD"},
    {"currency" => "IDR - Indonesian Rupiah", "initialism" => "IDR"},
    {"currency" => "ILS - Israeli Shekel", "initialism" => "ILS"},
    {"currency" => "INR - Indian Rupee", "initialism" => "INR"},
    {"currency" => "KRW - South Korean Won", "initialism" => "KRW"},
    {"currency" => "MXN - Mexican Peso", "initialism" => "MXN"},
    {"currency" => "MYR - Malaysian Ringgit", "initialism" => "MYR"},
    {"currency" => "NZD - New Zealand Dollar ", "initialism" => "NZD"},
    {"currency" => "PHP - Philippine Peso", "initialism" => "PHP"},
    {"currency" => "SGD - Singapore Dollar", "initialism" => "SGD"},
    {"currency" => "THB - Thai Baht", "initialism" => "THB"},
    {"currency" => "ZAR - South African Rand", "initialism" => "ZAR"}
]
